networks:
  frappe-network:
    name: frappe-network
    external: true

volumes:
  frappe16-mariadb-vol:
    external: true
    name: frappe16-mariadb-vol
  frappe16-redis-cache-data:
    external: true
    name: frappe16-redis-cache-data
  frappe16-redis-queue-data:
    external: true
    name: frappe16-redis-queue-data
  frappe16-redis-socketio-data:
    external: true
    name: frappe16-redis-socketio-data
  # postgresql-vol:

services:
  mariadb:
    image: docker.io/mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
      - --max_allowed_packet=512M
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_ROOT_USER: root
    volumes:
      - frappe16-mariadb-vol:/var/lib/mysql
    networks:
      - frappe-network
    ports:
      - "33066:3306"

  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   restart: on-failure
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data

  redis-cache:
    image: docker.io/redis:alpine
    volumes:
      - frappe16-redis-cache-data:/data
    networks:
      - frappe-network

  redis-queue:
    image: docker.io/redis:alpine
    volumes:
      - frappe16-redis-queue-data:/data
    networks:
      - frappe-network

  redis-socketio:
    image: docker.io/redis:alpine
    volumes:
      - frappe16-redis-socketio-data:/data
    networks:
      - frappe-network

  frappe:
    build: .
    command: bash -c "cd frappe-bench;bench start"
    # command: sleep infinity
    user: frappe:frappe
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - ../../frappe_docker_16:/workspace
      - /home/${USER}/.ssh/known_hosts:/home/frappe/.ssh/known_hosts
      - /home/${USER}/.bash_history:/home/frappe/.bash_history
      - /home/${USER}/.gitconfig:/home/frappe/.gitconfig
      - .bash_aliases:/home/frappe/.bash_aliases
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    working_dir: /workspace/development/
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"
      - "587:587"
      - "143:143"
      - "5432:5432"
    networks:
      - frappe-network

  greenmail:
    image: docker.io/greenmail/standalone
    ports:
      - "6081:8080"
    networks:
      - frappe-network

  roundcube:
    image: docker.io/roundcube/roundcubemail
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: greenmail
      ROUNDCUBEMAIL_DEFAULT_PORT: 3143
      ROUNDCUBEMAIL_SMTP_SERVER: greenmail
      ROUNDCUBEMAIL_SMTP_PORT: 3025
    ports:
      - "6082:80"
    networks:
      - frappe-network

  nodejs:
    image: docker.io/node:lts
    user: node:node
    networks:
      - frappe-network
    volumes:
      #this app is a clone from https://github.com/FHenry/frappe_erpnext_nodejs_poc.git
      - ../../frappe_erpnext_nodejs_poc:/home/node/app
    ports:
      - "8888:8888"
    working_dir: /home/node/app
    command: sleep infinity
